rust:
  - stable
  - beta
  - nightly
cache: cargo
before_install:
  - '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get update -qq || brew update'
install:
  - '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get install -y libsdl1.2-dev || brew install sdl'language: rust
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
