before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
